In [11]:
a = 1
b = 2

In [1]:
b = 512

In [6]:
c = 1000
d = 999

In [ ]:
print(a)

In [22]:
a + b

513

In [24]:
def add(x,y):
    return x+y

In [2]:
add(a,b)

NameError: name 'add' is not defined

In [10]:
import requests
import numpy as np
import pandas as pd

In [10]:
# print(numpy.__version__)

1.23.2


In [11]:
# print(pandas.__version__)

1.4.2


In [16]:
np.random.rand(5,5)

array([[0.38880858, 0.88407921, 0.65689313, 0.51928885, 0.29033654],
       [0.61466675, 0.97692045, 0.29633504, 0.9197736 , 0.74438104],
       [0.19323487, 0.84696305, 0.05777757, 0.51898715, 0.31326248],
       [0.23913531, 0.26692235, 0.10981419, 0.2088569 , 0.83568337],
       [0.86668773, 0.77505586, 0.27511612, 0.60000117, 0.04216048]])

In [17]:
np.random.randint(0,high=100,size=(5,5))

array([[37, 71, 16, 99, 13],
       [43, 37, 50, 97, 62],
       [24, 41, 71, 60, 64],
       [66, 88,  6, 44, 99],
       [35, 92, 63, 22, 79]])

In [ ]:
def sum(end):
    n = 0
    for i in range(end):
        n += i
    return n

In [ ]:
np.arange(0,100,4)

In [ ]:
%%timeit [1,1]
x = sum(1000)
# print(x)


In [ ]:
%lsmagic

In [ ]:
%ls


# asfdasf
![dog](https://cdn.cnn.com/cnnnext/dam/assets/201030094143-stock-rhodesian-ridgeback-exlarge-169.jpg)

In [13]:
def sum(end):
    n = 0
    for i in range(end):
        n += i
    return n

In [19]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [43]:
%%timeit [1,1]
x = sum(1000)
# print(x)


47.1 µs ± 4.96 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [38]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [ ]:
%ls


# asfdasf
![dog](https://cdn.cnn.com/cnnnext/dam/assets/201030094143-stock-rhodesian-ridgeback-exlarge-169.jpg)